version: '3.8'

services:
  nvim:
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
    ports:
      - "4200:4200"
      - "3000:3000"
    volumes:
      - ./projects/:/root/workspace
      - ./config/:/root/.config/nvim

